### ISSUE TITLE
Javascript error on OSX installer

### ISSUE THREAD

**Issue by ArayB** [sqlectron/sqlectron-gui#123]
Hi, tried to install this and get the following error:

**A JavaScript error occurred in the main process**

Uncaught Exception:
Error: Cannot find module '../../../app/package.json'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Applications/Sqlectron.app/Contents/Resources/app.asar/out/browser/menu/darwin.js:14:23)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)

OSX 10.10.5
Node 4.4.3

I had no problems installing on Ubuntu a couple of days ago.

**Comment by maxcnunes** [comment]
Using the version 1.6.2 - https://github.com/sqlectron/sqlectron-gui/releases/download/v1.6.2/Sqlectron-1.6.2.dmg ?
It is working for me: OSX 10.11.4.

**Comment by ArayB** [comment]
I was trying to install 1.6.0 apparently. 
That has installed fine now.
Was a bit weird because a colleague had no problems installing either.

Thanks!

**Comment by maxcnunes** [comment]
Thanks. That was a bug created on version 1.6.0 and fixed on version 1.6.1. Glad is working now for you.
