### ISSUE TITLE
Cant run development

### ISSUE THREAD

**Issue by bryantmakesprog** [sqlectron/sqlectron-gui#228]
I can't seem to bring up the development environment. To be fair, this is the first project like this I've tried to setup though, so I could be doing something wrong. I'm using node v6.

**I Did This:**

Ran `npm run dev`

**I Expected This:**

Sqlectron to come up

**Instead This Happened:**

I received the following error:
```
[electron] A JavaScript error occurred in the main process
[electron] Uncaught Exception:
[electron] Error: Cannot find module 'babel-register'
[electron]     at Module._resolveFilename (module.js:440:15)
[electron]     at Function.Module._resolveFilename (/home/bryant/projects/sqlectron/node_modules/electron-prebuilt/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
[electron]     at Function.Module._load (module.js:388:25)
[electron]     at Module.require (module.js:468:17)
[electron]     at require (internal/module.js:20:19)
[electron]     at Object.<anonymous> (/home/bryant/projects/sqlectron/src/browser/main.js:8:3)
[electron]     at Module._compile (module.js:541:32)
[electron]     at Object.Module._extensions..js (module.js:550:10)
[electron]     at Module.load (module.js:458:32)
[electron]     at tryModuleLoad (module.js:417:12)
```

Full Log:
```
➜  sqlectron git:(master) npm run dev

> @ dev /home/bryant/projects/sqlectron
> concurrently --names 'webpack,electron' --prefix name 'npm run dev:webpack' 'npm run dev:electron'

[electron] 
[electron] > @ dev:electron /home/bryant/projects/sqlectron
[electron] > cross-env DEBUG=sqlectron-gui:*,sqlectron-core:*,spawn-auto-restart node scripts/dev-auto-restart.js
[electron] 
[webpack] 
[webpack] > @ dev:webpack /home/bryant/projects/sqlectron
[webpack] > webpack-dev-server --color --config ./webpack.dev.config.js
[webpack] 
[electron] Not watching changes on sqlectron-core
[electron] App threw an error during load
[electron] Error: Cannot find module 'babel-register'
[electron]     at Module._resolveFilename (module.js:440:15)
[electron]     at Function.Module._resolveFilename (/home/bryant/projects/sqlectron/node_modules/electron-prebuilt/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
[electron]     at Function.Module._load (module.js:388:25)
[electron]     at Module.require (module.js:468:17)
[electron]     at require (internal/module.js:20:19)
[electron]     at Object.<anonymous> (/home/bryant/projects/sqlectron/src/browser/main.js:8:3)
[electron]     at Module._compile (module.js:541:32)
[electron]     at Object.Module._extensions..js (module.js:550:10)
[electron]     at Module.load (module.js:458:32)
[electron]     at tryModuleLoad (module.js:417:12)
[electron] A JavaScript error occurred in the main process
[electron] Uncaught Exception:
[electron] Error: Cannot find module 'babel-register'
[electron]     at Module._resolveFilename (module.js:440:15)
[electron]     at Function.Module._resolveFilename (/home/bryant/projects/sqlectron/node_modules/electron-prebuilt/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
[electron]     at Function.Module._load (module.js:388:25)
[electron]     at Module.require (module.js:468:17)
[electron]     at require (internal/module.js:20:19)
[electron]     at Object.<anonymous> (/home/bryant/projects/sqlectron/src/browser/main.js:8:3)
[electron]     at Module._compile (module.js:541:32)
[electron]     at Object.Module._extensions..js (module.js:550:10)
[electron]     at Module.load (module.js:458:32)
[electron]     at tryModuleLoad (module.js:417:12)
[webpack]  http://localhost:8080/webpack-dev-server/
[webpack] webpack result is served from /static/
[webpack] content is served from /home/bryant/projects/sqlectron
```

**Comment by maxcnunes** [comment]
Hi @bryantmakesprog,

Before running the project you have to install the dependencies.

```bash
npm install
```

**Comment by bryantmakesprog** [comment]
Doing so seems to skip a number of dependencies:

```
➜  sqlectron git:(master) npm install

> undefined postinstall /home/bryant/projects/sqlectron
> install-app-deps

Installing app dependencies for arch x64 to /home/bryant/projects/sqlectron/app

/home/bryant/projects/sqlectron
├─┬ electron-builder@6.7.7 
│ └─┬ fs-extra-p@1.1.8
│   └─┬ fs-extra-tf@0.30.2
│     └── jsonfile@2.4.0 
├── UNMET PEER DEPENDENCY react@15.3.1
└── UNMET PEER DEPENDENCY react-dom@15.3.1

npm WARN optional Skipping failed optional dependency /babel-cli/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm WARN optional Skipping failed optional dependency /electron-builder/appdmg-tf:
npm WARN notsup Not compatible with your operating system or architecture: appdmg-tf@0.4.7
npm WARN optional Skipping failed optional dependency /7zip-bin/7zip-bin-win:
npm WARN notsup Not compatible with your operating system or architecture: 7zip-bin-win@2.0.1
npm WARN optional Skipping failed optional dependency /7zip-bin/7zip-bin-osx:
npm WARN notsup Not compatible with your operating system or architecture: 7zip-bin-osx@1.0.0
npm WARN optional Skipping failed optional dependency /spawn-auto-restart/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm WARN optional Skipping failed optional dependency /webpack/watchpack/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm WARN react-select@0.9.1 requires a peer of react@^0.14.1 but none was installed.
npm WARN react-select@0.9.1 requires a peer of react-dom@^0.14.1 but none was installed.
npm WARN sqlectron No repository field.
npm WARN sqlectron No license field.
```

**Comment by maxcnunes** [comment]
Could you try to run the app to check if it may work without those skipped deps?

If still not working. Could you let me know what OS you are using. And also the NPM version your are using (`npm --version`).

**Comment by bryantmakesprog** [comment]
I still get the same error when trying to run it. I believe I actually already did the `npm install` but couldn't recall for certain.

Ubuntu 14.04
NPM 3.10.3

**Comment by maxcnunes** [comment]
Well should work with your environment configuration. Sometime NPM mess up the installation, if something goes wrong like network failure. Could you try removing the `node_modules` and installing again?

**Comment by bryantmakesprog** [comment]
heh, that actually did it. Thanks!
