### ISSUE TITLE
Close connection button does not work when connected to MS SQL

### ISSUE THREAD

**Issue by bjhansen-ualr** [sqlectron/sqlectron-gui#270]
I only have this issue when I'm connected to an MS SQL server.

Upon clicking the button the Dev Tools report this error:
`Uncaught Error: Could not call remote function 'end'. Check that the function signature is correct. Underlying error: conn.close is not a function
Error: Could not call remote function 'end'. Check that the function signature is correct. Underlying error: conn.close is not a function
    at callFunction (/Applications/Sqlectron.app/Contents/Resources/electron.asar/browser/rpc-server.js:228:11)
    at EventEmitter.<anonymous> (/Applications/Sqlectron.app/Contents/Resources/electron.asar/browser/rpc-server.js:316:5)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:201:7)
    at WebContents.<anonymous> (/Applications/Sqlectron.app/Contents/Resources/electron.asar/browser/api/web-contents.js:219:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)`

**Comment by maxcnunes** [comment]
Hi @bjhansen-ualr, thanks for report the problem. My fault, I will fix that once I get some free time.
