### ISSUE TITLE
Invalid string length error

### ISSUE THREAD

**Issue by xkoenig** [sqlectron/sqlectron-gui#341]
I'm not sure exactly what is causing this problem when using Sqlectron to query my database. When I submit a small enough query (i.e. will return less than some maximum set of data) it completes as normal, however if not, I get this message (below). Can you help?

Invalid string length 
RangeError: Invalid string length at JSON.stringify (<anonymous>) at Event.set (/Applications/Sqlectron.app/Contents/Resources/electron.asar/browser/api/web-contents.js:252:37) at EventEmitter.<anonymous> (/Applications/Sqlectron.app/Contents/Resources/electron.asar/browser/rpc-server.js:387:23) at emitThree (events.js:116:13) at EventEmitter.emit (events.js:194:7) at WebContents.<anonymous> (/Applications/Sqlectron.app/Contents/Resources/electron.asar/browser/api/web-contents.js:256:37) at emitTwo (events.js:106:13) at WebContents.emit (events.js:191:7)

**Comment by maxcnunes** [comment]
Please what is the: OS, Sqlectron version and DB you are using?

**Comment by xkoenig** [comment]
Mac OS 10.12.6; sqlectron version 1.23.0. Database is my own work database

**Comment by maxcnunes** [comment]
But which database: MySQL, PostgreSQL, ...?

**Comment by xkoenig** [comment]
PostgreSQL

**Comment by maxcnunes** [comment]
Sorry, I can't reproduce this issue. Probably you will need to debug it in the source code or wait for someone else to do that.

**Comment by s-kem** [comment]
How many rows are you getting back when you make this query and what's the number of characters in a row?

My guess here is that the query is too large and required too much memory so it couldn't be properly parsed.
