### ISSUE TITLE
Bad input string while trying to connect

### ISSUE THREAD

**Issue by Nekromancer** [sqlectron/sqlectron-gui#343]
Hi,

I'm trying to use sqlectron on Windows to manage a SQLite database. But, when i'm trying to connect to database i get `Bad input string` error.

Whole log:
```
{"app":"sqlectron-gui","name":"sqlectron-gui","hostname":"jakub-pc","pid":10452,"namespace":"renderer:redux","level":50,"msg":"Error Error { message: 'Bad input string', name: 'TypeError' }","time":"2017-09-08T17:42:39.675Z","v":0}
{"app":"sqlectron-gui","name":"sqlectron-gui","hostname":"jakub-pc","pid":10452,"namespace":"renderer:redux","level":50,"msg":"Error Stack TypeError: Bad input string\n    at Decipher.update (crypto.js:145:26)\n    at Object.decrypt (C:\\Users\\Jakub\\AppData\\Local\\Programs\\Sqlectron\\resources\\app.asar\\node_modules\\sqlectron-core\\lib\\crypto.js:33:22)\n    at decryptSecrects (C:\\Users\\Jakub\\AppData\\Local\\Programs\\Sqlectron\\resources\\app.asar\\node_modules\\sqlectron-core\\lib\\servers.js:148:30)\n    at C:\\Users\\Jakub\\AppData\\Local\\Programs\\Sqlectron\\resources\\app.asar\\node_modules\\sqlectron-core\\lib\\servers.js:14:14\n    at Array.forEach (native)\n    at Object.<anonymous> (C:\\Users\\Jakub\\AppData\\Local\\Programs\\Sqlectron\\resources\\app.asar\\node_modules\\sqlectron-core\\lib\\servers.js:13:20)\n    at Generator.next (<anonymous>)\n    at step (C:\\Users\\Jakub\\AppData\\Local\\Programs\\Sqlectron\\resources\\app.asar\\node_modules\\sqlectron-core\\lib\\servers.js:111:191)\n    at C:\\Users\\Jakub\\AppData\\Local\\Programs\\Sqlectron\\resources\\app.asar\\node_modules\\sqlectron-core\\lib\\servers.js:111:361\n    at <anonymous>","time":"2017-09-08T17:42:39.676Z","v":0}
```

It's even more funny that "Test" (on connection settings) is showing that configuration is working

@EDIT: i tried to connect to Postgres database and i have exact same issue. Test is passing, but `Bad input string` on connecting. So it appears to be a global error for more then SQLite connection

**Comment by Nekromancer** [comment]
When i removed two unused connections the rest just started to work. I have no idea why, but it seems to be resolved..
