### ISSUE TITLE
Cannot read property 'level' of undefined

### ISSUE THREAD

**Issue by ma3ve** [sqlectron/sqlectron-gui#596]
While using ```npm run dev``` on source code  it gives this error ```Cannot read property 'level' of undefined```

error
```
[electron] [1] App threw an error during load
[electron] [1] TypeError: Cannot read property 'level' of undefined
[electron] [1]     at Object.getConfig (C:\learnElectron\sqlectron-gui\out\browser\config.js:64:34)
[electron] [1]     at Object.<anonymous> (C:\learnElectron\sqlectron-gui\out\browser\main.js:24:27)
[electron] [1]     at Module._compile (internal/modules/cjs/loader.js:968:30)
[electron] [1]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:986:10)
[electron] [1]     at Module.load (internal/modules/cjs/loader.js:816:32)
[electron] [1]     at Module._load (internal/modules/cjs/loader.js:728:14)
[electron] [1]     at Function.Module._load (electron/js2c/asar.js:748:26)
[electron] [1]     at loadApplicationPackage (C:\learnElectron\sqlectron-gui\node_modules\electron\dist\resources\default_app.asar\main.js:109:16)        
[electron] [1]     at Object.<anonymous> (C:\learnElectron\sqlectron-gui\node_modules\electron\dist\resources\default_app.asar\main.js:155:9)
[electron] [1]     at Module._compile (internal/modules/cjs/loader.js:968:30)
```

full log
```
> sqlectron@1.35.0 dev C:\learnElectron\sqlectron-gui
> cross-env NODE_ENV=development concurrently --names "webpack,electron" --prefix name "npm run dev:webpack" "npm run dev:electron"

[webpack] 
[webpack] > sqlectron@1.35.0 dev:webpack C:\learnElectron\sqlectron-gui
[webpack] > webpack-dev-server --color
[webpack]
[electron] 
[electron] > sqlectron@1.35.0 dev:electron C:\learnElectron\sqlectron-gui
[electron] > npm run compile:browser && concurrently --kill-others --names "build,run" "npm run compile:browser -- -w" "cross-env DEBUG=spawn-auto-restart node scripts/dev-auto-restart.js | bunyan -o short"
[electron]
[electron] 
[electron] > sqlectron@1.35.0 compile:browser C:\learnElectron\sqlectron-gui
[electron] > tsc --project tsconfig.build.json
[electron]
[webpack] i ｢wds｣: Project is running at http://localhost:8080/
[webpack] i ｢wds｣: webpack output is served from /static/
[webpack] i ｢wds｣: Content not from webpack is served from C:\learnElectron\sqlectron-gui
[electron] [1] Not watching changes on sqlectron-db-core
[electron] [1]
[electron] [0]
[electron] [0] > sqlectron@1.35.0 compile:browser C:\learnElectron\sqlectron-gui
[electron] [0] > tsc --project tsconfig.build.json "-w"
[electron] [0]
[electron] [0]
[electron] [0] 4:44:15 pm - Starting compilation in watch mode...
[electron] [0]
[electron] [1] App threw an error during load
[electron] [1] TypeError: Cannot read property 'level' of undefined
[electron] [1]     at Object.getConfig (C:\learnElectron\sqlectron-gui\out\browser\config.js:64:34)
[electron] [1]     at Object.<anonymous> (C:\learnElectron\sqlectron-gui\out\browser\main.js:24:27)
[electron] [1]     at Module._compile (internal/modules/cjs/loader.js:968:30)
[electron] [1]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:986:10)
[electron] [1]     at Module.load (internal/modules/cjs/loader.js:816:32)
[electron] [1]     at Module._load (internal/modules/cjs/loader.js:728:14)
[electron] [1]     at Function.Module._load (electron/js2c/asar.js:748:26)
[electron] [1]     at loadApplicationPackage (C:\learnElectron\sqlectron-gui\node_modules\electron\dist\resources\default_app.asar\main.js:109:16)        
[electron] [1]     at Object.<anonymous> (C:\learnElectron\sqlectron-gui\node_modules\electron\dist\resources\default_app.asar\main.js:155:9)
[electron] [1]     at Module._compile (internal/modules/cjs/loader.js:968:30)
[webpack] Browserslist: caniuse-lite is outdated. Please run:
[webpack] npx browserslist@latest --update-db
[electron] [1] 2021-03-09T11:14:21.521Z spawn-auto-restart restarting due changes
[electron] [1] 2021-03-09T11:14:21.578Z spawn-auto-restart restarting due changes
[electron] [1] 2021-03-09T11:14:21.609Z spawn-auto-restart restarting due changes
[electron] [1] 2021-03-09T11:14:21.665Z spawn-auto-restart restarting due changes
[electron] [1] 2021-03-09T11:14:21.691Z spawn-auto-restart restarting due changes
[electron] [1] 2021-03-09T11:14:21.696Z spawn-auto-restart restarting due changes
[electron] [1] 2021-03-09T11:14:21.724Z spawn-auto-restart restarting due changes
[electron] [1] 2021-03-09T11:14:21.726Z spawn-auto-restart restarting due changes
[electron] [1] 2021-03-09T11:14:21.752Z spawn-auto-restart restarting due changes
[electron] [1] 2021-03-09T11:14:21.755Z spawn-auto-restart restarting due changes
[electron] [1] 2021-03-09T11:14:21.757Z spawn-auto-restart restarting due changes
[electron] [1] 2021-03-09T11:14:21.783Z spawn-auto-restart restarting due changes
[electron] [1] 2021-03-09T11:14:21.785Z spawn-auto-restart restarting due changes
[electron] [1] 2021-03-09T11:14:21.813Z spawn-auto-restart restarting due changes
[electron] [1] 2021-03-09T11:14:21.816Z spawn-auto-restart restarting due changes
[electron] [1] 2021-03-09T11:14:21.839Z spawn-auto-restart restarting due changes
[electron] [1] 2021-03-09T11:14:21.847Z spawn-auto-restart restarting due changes
[electron] [1] 2021-03-09T11:14:21.847Z spawn-auto-restart restarting due changes
[electron] [1] 2021-03-09T11:14:21.847Z spawn-auto-restart restarting due changes
[electron] [0] 
[electron] [0] 4:44:21 pm - Found 0 errors. Watching for file changes.
[electron] [1] 
[electron] [1] App threw an error during load
[electron] [1] TypeError: Cannot read property 'level' of undefined
[electron] [1]     at Object.getConfig (C:\learnElectron\sqlectron-gui\out\browser\config.js:64:34)
[electron] [1]     at Object.<anonymous> (C:\learnElectron\sqlectron-gui\out\browser\main.js:24:27)
[electron] [1]     at Module._compile (internal/modules/cjs/loader.js:968:30)
[electron] [1]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:986:10)
[electron] [1]     at Module.load (internal/modules/cjs/loader.js:816:32)
[electron] [1]     at Module._load (internal/modules/cjs/loader.js:728:14)
[electron] [1]     at Function.Module._load (electron/js2c/asar.js:748:26)
[electron] [1]     at loadApplicationPackage (C:\learnElectron\sqlectron-gui\node_modules\electron\dist\resources\default_app.asar\main.js:109:16)        
[electron] [1]     at Object.<anonymous> (C:\learnElectron\sqlectron-gui\node_modules\electron\dist\resources\default_app.asar\main.js:155:9)
[electron] [1]     at Module._compile (internal/modules/cjs/loader.js:968:30)
[webpack] i ｢wdm｣: Hash: 8daa266775b9db31f885
[webpack] Version: webpack 4.44.1
[webpack] Time: 15359ms
[webpack] Built at: 09/03/2021 4:44:24 pm
[webpack]                                                                        Asset      Size  Chunks             Chunk Names
[webpack]                         _/vendor/renderer/lato/fonts/Lato-Regular-19df47.eot   248 KiB          [emitted]
[webpack]                        _/vendor/renderer/lato/fonts/Lato-Regular-1d2ca9.woff   302 KiB          [emitted]
[webpack]                       _/vendor/renderer/lato/fonts/Lato-Regular-75614c.woff2   178 KiB          [emitted]
[webpack]                         _/vendor/renderer/lato/fonts/Lato-Regular-bb14dc.ttf   593 KiB          [emitted]
[webpack]   _/vendor/renderer/semantic-ui/themes/default/assets/fonts/icons-03605b.eot  59.3 KiB          [emitted]
[webpack]   _/vendor/renderer/semantic-ui/themes/default/assets/fonts/icons-45f9f9.ttf   119 KiB          [emitted]
[webpack]  _/vendor/renderer/semantic-ui/themes/default/assets/fonts/icons-c589f7.woff  69.8 KiB          [emitted]
[webpack]   _/vendor/renderer/semantic-ui/themes/default/assets/fonts/icons-d0ba16.svg   306 KiB          [emitted]
[webpack] _/vendor/renderer/semantic-ui/themes/default/assets/fonts/icons-fb685a.woff2  55.4 KiB          [emitted]
[webpack]                                                                    bundle.js  27.5 MiB     app  [emitted]  app
[webpack]                                                                   index.html  2.17 KiB          [emitted]
[webpack] Entrypoint app = bundle.js
[webpack] [0] multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/renderer/entry.tsx 52 bytes {app} [built]
[webpack] [./node_modules/react-dom/index.js] 1.33 KiB {app} [built]
[webpack] [./node_modules/react-redux/es/index.js] 776 bytes {app} [built]
[webpack] [./node_modules/react-router/es/index.js] 1.43 KiB {app} [built]
[webpack] [./node_modules/react/index.js] 190 bytes {app} [built]
[webpack] [./node_modules/strip-ansi/index.js] 161 bytes {app} [built]
[webpack] [./node_modules/webpack-dev-server/client/index.js?http://localhost:8080] (webpack)-dev-server/client?http://localhost:8080 4.29 KiB {app} [built]
[webpack] [./node_modules/webpack-dev-server/client/overlay.js] (webpack)-dev-server/client/overlay.js 3.51 KiB {app} [built]
[webpack] [./node_modules/webpack-dev-server/client/socket.js] (webpack)-dev-server/client/socket.js 1.53 KiB {app} [built]
[webpack] [./node_modules/webpack-dev-server/client/utils/createSocketUrl.js] (webpack)-dev-server/client/utils/createSocketUrl.js 2.91 KiB {app} [built] 
[webpack] [./node_modules/webpack-dev-server/client/utils/log.js] (webpack)-dev-server/client/utils/log.js 964 bytes {app} [built]
[webpack] [./node_modules/webpack-dev-server/client/utils/reloadApp.js] (webpack)-dev-server/client/utils/reloadApp.js 1.59 KiB {app} [built]
[webpack] [./node_modules/webpack-dev-server/client/utils/sendMessage.js] (webpack)-dev-server/client/utils/sendMessage.js 402 bytes {app} [built]        
[webpack] [./node_modules/webpack/hot/dev-server.js] (webpack)/hot/dev-server.js 1.59 KiB {app} [built]
[webpack] [./src/renderer/entry.tsx] 1.3 KiB {app} [built]
[webpack]     + 585 hidden modules
[webpack] Child HtmlWebpackCompiler:
[webpack]      1 asset
[webpack]     Entrypoint HtmlWebpackPlugin_0 = __child-HtmlWebpackPlugin_0
[webpack]     [./node_modules/html-webpack-plugin/lib/loader.js!./src/renderer/index.html] 2.6 KiB {HtmlWebpackPlugin_0} [built]
[webpack] i ｢wdm｣: Compiled successfully.
```

**Comment by MasterOdin** [comment]
Thanks for reporting this error. This should be fixed once #598 is merged.
